--------------------------------------------------------------------
--INSTAED OF LIBRARY & BOOKS , I HAVE TAKEN STUDENT & TRANSPORT DETAILS for practice
--------------------------------------------------------------------


CREATE TABLE XX_STUD(
STU_ID VARCHAR(5) NOT NULL,
NAME VARCHAR(50),
LOCATION VARCHAR(50),
CONSTRAINT STU_PK PRIMARY KEY(LOCATION));

CREATE TABLE XX_LOCATION_STUD(
ZONEID NUMBER(20) NOT NULL PRIMARY KEY,
LOCATION VARCHAR(50) NOT NULL,
NO_OF_STUDENTS NUMBER(20) NOT NULL,
CONSTRAINT LOC_FK FOREIGN KEY(LOCATION) REFERENCES XX_STUD(LOCATION));

CREATE TABLE XX_TRANSPORT(
ZONEID NUMBER(20) NOT NULL,
DRIVER_NAME VARCHAR(20) NOT NULL,
DRIVER_BUS_DETAILS VARCHAR(50) NOT NULL,
DRIVER_BIO VARCHAR(30) NOT NULL,
DRIVER_PHONE NUMBER(10) NOT NULL,
CONSTRAINT TRAN_FK FOREIGN KEY(ZONEID) REFERENCES XX_LOCATION_STUD(ZONEID));
     
------------------------------------------------
--     Banking Management System
--Table1- CUSTOMER_PERSONAL_INFO
--Table2 - BANK_INFO
--Table3 - ACCOUNT_INFO
------------------------------------------------
     
CREATE TABLE XX_CUST_PERSONAL_INFO(
CUST_FNAME VARCHAR(20) NOT NULL,CUST_LNAME VARCHAR(20) NOT NULL,
CUST_ID NUMBER(20) PRIMARY KEY,
CUST_ACC_TYPE VARCHAR(20) NOT NULL,
CUST_ACC_NUM NUMBER(20) NOT NULL,
CUST_POSTAL_CODE NUMBER(10) NOT NULL,
CUST_DOB DATE NOT NULL,
CUST_GENDER VARCHAR(20),
CUST_AGE_CATEGORY VARCHAR(20) NOT NULL,
CUST_NATIONALITY VARCHAR(20) NOT NULL,
CUST_PHONE NUMBER(10) NOT NULL,
CUST_AADHAR NUMBER(12) NOT NULL,
CUST_VOTER_ID NUMBER(14) NOT NULL,
CUST_PAN NUMBER(12) NOT NULL,
CUST_ADDRESS VARCHAR(20) NOT NULL,
BANK_ID VARCHAR(20) NOT NULL,
BANK_NAME VARCHAR(20) NOT NULL,
BANK_IFSC_CODE VARCHAR(20) NOT NULL
);

--DROP TABLE XX_CUST_PERSONAL_INFO;
DROP TABLE XX_BANK_INFORMATION;
-- RENAME XX_CUSTOMER_PERSONAL TO XX_CUST_PERSONAL_INFO;

CREATE TABLE XX_BANK_INFORMATION(
CUST_ID NUMBER(20) NOT NULL,
BANK_ID VARCHAR(20) NOT NULL,
BANK_NAME VARCHAR(20) NOT NULL,
BANK_ADDRESS VARCHAR(20) NOT NULL,
BANK_IFSC_CODE VARCHAR(20) NOT NULL,
BANK_BRANCH VARCHAR(20) NOT NULL,
BANK_CITY VARCHAR(20) NOT NULL,
BANK_POSTAL_CODE VARCHAR(20) NOT NULL,
CONSTRAINT BNK_PK PRIMARY KEY(CUST_ID),
CONSTRAINT BNK_FK FOREIGN KEY(CUST_ID) REFERENCES XX_CUST_PERSONAL_INFO(CUST_ID)
);

--DROP TABLE XX_ACCOUNT_INFORMATION;

CREATE TABLE XX_ACCOUNT_INFORMATION(
CUST_ID NUMBER(20) NOT NULL PRIMARY KEY,
ACCOUNT_CATEGORY VARCHAR(20) NOT NULL,
ACCOUNT_BALANCE NUMBER(100),
ACCOUNT_TYPE VARCHAR(20) NOT NULL,
ACCOUNT_HISTORY VARCHAR(20) NOT NULL,
CONSTRAINT ACC_FK FOREIGN KEY(CUST_ID) REFERENCES XX_CUST_PERSONAL_INFO(CUST_ID)
);

----------------------------------------
-----------------------------------------